-- CRIANDO TABELA EMPRESA
CREATE TABLE EMPRESA (
COD_EMPRESA INT NOT NULL PRIMARY KEY,
NOME_EMPRESA VARCHAR2(50),
FANTASIA VARCHAR2(15)
);

-- CRIANDO SEQUENCIA PARA O CODIGO EMPRESA
CREATE SEQUENCE SEQ_EMP START WITH 1 INCREMENT BY 1 NOMAXVALUE;

-- CADASTRO DE UNIDADE FEDERAL, UTILIZADO POR TODAS EMPRESAS
-- DROP TABLE UF;
CREATE TABLE UF (
COD_UF VARCHAR2(2) NOT NULL PRIMARY KEY,
SIGLA_UF VARCHAR2(2) NOT NULL,
NOME_UF VARCHAR2(30) NOT NULL
);

-- TABLE CIDADES
-- CADASTRO DE CIDADES, UTILIZADO POR TODAS EMPRESAS
-- DROP TABLE CIDADES;

CREATE TABLE CIDADES (
    COD_CIDADE VARCHAR2(7) NOT NULL PRIMARY KEY,
    COD_UF VARCHAR(2) NOT NULL,
    NOME_CIDADE VARCHAR2(50) NOT NULL,
    CONSTRAINT FK_CID1 FOREIGN KEY (COD_UF) REFERENCES UF(COD_UF)
    );
    

CREATE TABLE CLIENTES(
    COD_EMPRESA     INT                NOT NULL  PRIMARY KEY,
    ID_CLIENTE      INT                NOT NULL,              
    RAZAO_CLIENTE   VARCHAR2(100)      NOT NULL,            
    FANTASIA        VARCHAR2(15)       NOT NULL,        
    ENDERECO        VARCHAR2(50)       NOT NULL,        
    NRO             VARCHAR2(10)       NOT NULL,
    BAIRRO          VARCHAR2(20)       NOT NULL,    
    COD_CIDADE      VARCHAR2(7)        NOT NULL,        
    CEP             VARCHAR2(8)        NOT NULL,
    CNPJ_CPF        VARCHAR2(15)       NOT NULL,        
    TIPO_CLIENTE    CHAR(1)                      CONSTRAINT CK_TC1 CHECK (TIPO_CLIENTE IN ('F', 'J')),
    DATA_CADASTRO   DATE               NOT NULL,              
    COD_PAGTO       INT,
    CONSTRAINT FK_COD_EMP1  FOREIGN KEY (COD_EMPRESA) REFERENCES EMPRESA(COD_EMPRESA),
    CONSTRAINT FK_CLI1      FOREIGN KEY (COD_EMPRESA) REFERENCES EMPRESA(COD_EMPRESA)
);











    
    
    