-- CRIANDO TABELA EMPRESA
CREATE TABLE EMPRESA (
COD_EMPRESA INT NOT NULL PRIMARY KEY,
NOME_EMPRESA VARCHAR2(50),
FANTASIA VARCHAR2(15)
);

-- CRIANDO SEQUENCIA PARA O CODIGO EMPRESA
CREATE SEQUENCE SEQ_EMP START WITH 1 INCREMENT BY 1 NOMAXVALUE;

-- CADASTRO DE UNIDADE FEDERAL, UTILIZADO POR TODAS EMPRESAS
-- DROP TABLE UF;
CREATE TABLE UF (
COD_UF VARCHAR2(2) NOT NULL PRIMARY KEY,
SIGLA_UF VARCHAR2(2) NOT NULL,
NOME_UF VARCHAR2(30) NOT NULL
);

-- TABLE CIDADES
-- CADASTRO DE CIDADES, UTILIZADO POR TODAS EMPRESAS
-- DROP TABLE CIDADES;

CREATE TABLE CIDADES (
    COD_CIDADE VARCHAR2(7) NOT NULL PRIMARY KEY,
    COD_UF VARCHAR(2) NOT NULL,
    NOME_CIDADE VARCHAR2(50) NOT NULL,
    CONSTRAINT FK_CID1 FOREIGN KEY (COD_UF) REFERENCES UF(COD_UF)
    );
    

CREATE TABLE CLIENTES(
    COD_EMPRESA     INT                NOT NULL  PRIMARY KEY,
    ID_CLIENTE      INT                NOT NULL,              
    RAZAO_CLIENTE   VARCHAR2(100)      NOT NULL,            
    FANTASIA        VARCHAR2(15)       NOT NULL,        
    ENDERECO        VARCHAR2(50)       NOT NULL,        
    NRO             VARCHAR2(10)       NOT NULL,
    BAIRRO          VARCHAR2(20)       NOT NULL,    
    COD_CIDADE      VARCHAR2(7)        NOT NULL,        
    CEP             VARCHAR2(8)        NOT NULL,
    CNPJ_CPF        VARCHAR2(15)       NOT NULL,        
    TIPO_CLIENTE    CHAR(1)                      CONSTRAINT CK_TC1 CHECK (TIPO_CLIENTE IN ('F', 'J')),
    DATA_CADASTRO   DATE               NOT NULL,              
    COD_PAGTO       INT,
    CONSTRAINT FK_COD_EMP1  FOREIGN KEY (COD_EMPRESA)   REFERENCES EMPRESA(COD_EMPRESA),
    CONSTRAINT FK_CLI1      FOREIGN KEY (COD_CIDADE)    REFERENCES CIDADES(COD_CIDADE)
);

-- CRIANDO SEQUENCIA PARA CLIENTES

CREATE SEQUENCE SEQ_CLI START WITH 1 INCREMENT BY 1 NOMAXVALUE;

-- CRIACAO TABELA FORNECEDORES
CREATE TABLE FORNECEDORES (
    COD_EMPRESA     INT                NOT NULL,
    ID_FOR          INT                NOT NULL  PRIMARY KEY,              
    RAZAO_FORNEC    VARCHAR2(100)      NOT NULL,            
    FANTASIA        VARCHAR2(15)       NOT NULL,        
    ENDERECO        VARCHAR2(50)       NOT NULL,        
    NRO             VARCHAR2(10)       NOT NULL,
    BAIRRO          VARCHAR2(20)       NOT NULL,    
    COD_CIDADE      VARCHAR2(7)        NOT NULL,        
    CEP             VARCHAR2(8)        NOT NULL,
    CNPJ_CPF        VARCHAR2(15)       NOT NULL,        
    TIPO_FORNEC     CHAR(1)                      CONSTRAINT CK_TF1 CHECK (TIPO_FORNEC IN ('F', 'J')),
    DATA_CADASTRO   DATE               NOT NULL,              
    COD_PAGTO       INT,
    CONSTRAINT FK_COD_EMP2  FOREIGN KEY (COD_EMPRESA)   REFERENCES EMPRESA(COD_EMPRESA),
    CONSTRAINT FK_FOR1      FOREIGN KEY (COD_CIDADE)    REFERENCES CIDADES(COD_CIDADE)
);



-- CRIANDO SEQUENCIA PARA FORNECDORES
CREATE SEQUENCE SEQ_FOR START WITH 1 INCREMENT BY 1 NOMAXVALUE;

-- TABELAS TIPO DE MATERIAL
CREATE TABLE TIPO_MAT
(
    COD_TIPO_MAT    INT NOT NULL    PRIMARY KEY,
    DESC_TIPO_MAT   VARCHAR2(20)    NOT NULL
);

-- CRIANDO SEQUENCIA TIPO MATERIAL
CREATE SEQUENCE SEQ_TIP_MAT START WITH 1 INCREMENT BY 1 NOMAXVALUE;

-- CRIANDO TABELAS MATERIAL

CREATE TABLE MATERIAL
(
    COD_EMPRESA     INT             NOT NULL,
    COD_MAT         INT             NOT NULL,
    DESCRICAO       VARCHAR2(50)    NOT NULL,
    PRECO_UNIT      INT             NOT NULL,
    COD_TIPO_MAT    INT             NOT NULL,
    CONSTRAINT      FK_COD_EMP3     FOREIGN KEY (COD_EMPRESA)   REFERENCES EMPRESA  (COD_EMPRESA),  
    CONSTRAINT      FK_MAT1         FOREIGN KEY (COD_TIPO_MAT)  REFERENCES TIPO_MAT (COD_TIPO_MAT),
    CONSTRAINT      PK_EMP_MAT      PRIMARY KEY (COD_EMPRESA, COD_MAT) -- CHAVE PRIMARIA COMPOSTA
);


-- CRIANDO TABELA PARA FORNECEDORES DOS MATERIAS.
CREATE TABLE MAT_FORNEC
(
    COD_EMPRESA     INT     NOT NULL,
    COD_MAT         INT     NOT NULL,
    ID_FOR          INT     NOT NULL,
    CONSTRAINT      PK_MAT_FOR      PRIMARY KEY (COD_EMPRESA, COD_MAT, ID_FOR),
    CONSTRAINT      FK_MAT_FOR1     FOREIGN KEY (COD_EMPRESA)   REFERENCES EMPRESA(COD_EMPRESA),
    CONSTRAINT      FK_MAT_FOR2     FOREIGN KEY (ID_FOR)        REFERENCES FORNECEDORES(ID_FOR)
);

-- CRIANDO INDEX
-- SIMULA ERRO INDEX DE CHAVE PRIMARIA
-- CREATE INDEX IX_MAT1 ON MATERIAL(COD_EMPRESA, COD_MAT);
-- CRIANDO INDEX TIPO MATG
CREATE INDEX IX_MAT2 ON MATERIAL(COD_TIPO_MAT);

-- PRODUCAO
CREATE TABLE ORDEM_PROD
(
    COD_EMPRESA     INT             NOT NULL,
    ID_ORDEM        INT             NOT NULL    PRIMARY KEY,
    COD_MAT_PROD    INT             NOT NULL,
    QTD_PLAN        DECIMAL(10,2)   NOT NULL,
    QTD_PROD        DECIMAL(10,2)   NOT NULL,
    DATA_INI        DATE,
    DATA_FIM        DATE,
    SITUACAO        CHAR(1)         CONSTRAINT  CK_OP1 (SITUACAO IN ('A','P','F')), -- A-ABERTA, P-PLANEJADA, F-FECHADA
    CONSTRAINT      FK_OP1          FOREIGN KEY (COD_MAT_PROD, COD_EMPRESA) REFERENCES MATERIAL(COD_MAT, COD_EMPRESA)
  --CONSTRAINT      FK_COD_EMP4   FOREIGN KEY (COD_EMPRESA)               REFERENCES EMPRESA(COD_EMPRESA)
)

